//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autopilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class flughafen
    {
        public int flh_id { get; set; }
        public string flh_name { get; set; }
        public string flh_stadt { get; set; }
        public string flh_land { get; set; }
        public string flh_iatacode { get; set; }
        public string flh_icaocode { get; set; }
        public string flh_latitude { get; set; }
        public string flh_longitude { get; set; }
        public string flh_altitude { get; set; }
        public string flh_zeitzone { get; set; }
        public string flh_dst { get; set; }
        public string flh_zeitzone_base { get; set; }
    }
}
