//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autopilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class flugzeugliste
    {
        public int flz_id { get; set; }
        public int sta_id { get; set; }
        public string sta_bez { get; set; }
        public string her_bez { get; set; }
        public string ftyp_bez { get; set; }
        public string flz_kennzeichen { get; set; }
        public int ftyp_id { get; set; }
    }
}
