//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autopilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class flugzeugtyp
    {
        public int ftyp_id { get; set; }
        public string ftyp_bez { get; set; }
        public Nullable<decimal> ftyp_fkosten_pa { get; set; }
        public Nullable<int> her_id { get; set; }
        public Nullable<decimal> ftyp_speed { get; set; }
        public Nullable<int> twa_id { get; set; }
        public Nullable<decimal> ftyp_anz_fcrew { get; set; }
        public Nullable<decimal> ftyp_anz_ccrew { get; set; }
        public Nullable<decimal> ftyp_anz_pass { get; set; }
        public Nullable<decimal> ftyp_reichweite_km { get; set; }
        public Nullable<decimal> ftyp_anz_triebwerke { get; set; }
        public Nullable<decimal> ftyp_vkosten_ph { get; set; }
    }
}
