//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autopilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kundenliste
    {
        public int knd_id { get; set; }
        public int kng_id { get; set; }
        public string kng_bez { get; set; }
        public int anr_id { get; set; }
        public string anr_bez { get; set; }
        public Nullable<int> tit_id { get; set; }
        public string tit_bez { get; set; }
        public string knd_name { get; set; }
        public string knd_vorname { get; set; }
        public string anschrift { get; set; }
    }
}
