//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autopilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class kunde
    {
        public int knd_id { get; set; }
        public Nullable<int> kng_id { get; set; }
        public Nullable<int> anr_id { get; set; }
        public Nullable<int> tit_id { get; set; }
        public string knd_name { get; set; }
        public string knd_vorname { get; set; }
        public string knd_strasse { get; set; }
        public string knd_ort { get; set; }
        public string knd_plz { get; set; }
        public string knd_land { get; set; }
        public string knd_mail { get; set; }
        public string knd_telefon { get; set; }
    }
}
