//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autopilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahnstufe
    {
        public int mst_id { get; set; }
        public Nullable<int> mst_reihenfolge { get; set; }
        public Nullable<decimal> mst_tage { get; set; }
        public Nullable<decimal> mst_zuschlag { get; set; }
    }
}
