//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autopilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalliste
    {
        public int per_id { get; set; }
        public int sta_id { get; set; }
        public int pos_id { get; set; }
        public string sta_bez { get; set; }
        public string part_bez { get; set; }
        public string pos_bez { get; set; }
        public string per_name { get; set; }
        public string per_vorname { get; set; }
        public Nullable<decimal> pos_gehalt_pa { get; set; }
    }
}
