//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autopilot
{
    using System;
    using System.Collections.Generic;
    
    public partial class termin_personal
    {
        public int ter_id { get; set; }
        public int per_id { get; set; }
    }
}
